{% set version = "0.1-10" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-audio
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/audio_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/audio/audio_{{ version }}.tar.gz
  sha256: 82c731a88c741a6b4efe5069ce7dc2f765932d769323ac8d3fbb84ac30afc4dd

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('audio')"           # [not win]
    - "\"%R%\" -e \"library('audio')\""  # [win]

about:
  home: http://www.rforge.net/audio/
  license: MIT
  summary: Interfaces to audio devices (mainly sample-based) from R to allow recording and playback of audio. Built-in devices include Windows MM, Mac OS X AudioUnits and PortAudio (the last one is very experimental).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - mfansler

# Package: audio
# Version: 0.1-8
# Title: Audio Interface for R
# Author: Simon Urbanek <simon.urbanek@r-project.org>
# Maintainer: Simon Urbanek <simon.urbanek@r-project.org>
# Depends: R (>= 2.0.0)
# Description: Interfaces to audio devices (mainly sample-based) from R to allow recording and playback of audio. Built-in devices include Windows MM, Mac OS X AudioUnits and PortAudio (the last one is very experimental).
# License: MIT + file LICENSE
# URL: http://www.rforge.net/audio/
# NeedsCompilation: yes
# Packaged: 2021-09-08 04:44:17 UTC; rforge
# Repository: CRAN
# Date/Publication: 2021-09-08 06:12:23 UTC
